<a href="https://colab.research.google.com/github/dyong00/2020-2-AI/blob/master/code/01_tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#버전1.x

In [ ]:
#버전 변경 case1_기본
%tensorflow_version 1.x 

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `1.x #버전 변경`. This will be interpreted as: `1.x`.


TensorFlow 1.x selected.


In [ ]:
#버전 변경 case2_예외 제어
try:
    %tensorflow_version 1.x #매직 명령어
except Exception:
    pass

In [ ]:
import tensorflow as tf#tenseorflow객체를 import한 후 식별자를 tf로 지정

hello = tf.constant('Hello World!') #constant를 통해서 문자열 상수를 만듦
a = 10
b = 10

print(tf.add(a,b)) #Tensor("Add:0", shape=(), dtype=int32) 
#>>Tensor의 결과(Tensor의 name, 형태(스칼라 형식 값), 내부적인 데이터의 형식(int32타입))
#>>Tensor의 정보만 나오고 안에 저장되어 있는 값은 나오지 않는다.
#>>저장되어 있는 값(=20)이 나오게 하려면 Session을 부여해야 한다.

Tensor("Add:0", shape=(), dtype=int32)


In [ ]:
sess = tf.Session()
print(sess.run(tf.add(a,b))) #20 >>Session을 부여하여 저장되어있는 값을 출력
sess.close()

20


#버전 2.x

tensorflow객체 생성 및 버전 확인

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

객체의 정보 확인하기

In [ ]:
a = tf.constant(5) # Q. 그냥 a = 5 라고 쓰는 것과 무슨 차이일까?
b = tf.constant(3)
print(a+b) #tf.Tensor(8, shape=(), dtype=int32) 
#>> 1.x와 달리 Session을 사용하지 않아도 8이라는 Tensor의 결과가 나오는 것을 알 수 있음

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
c = tf.constant('Hello,world!')

print(c) #tf.Tensor(b'Hello,world!', shape=(), dtype=string)
#>> 여기서 b는 byte타입을 의미한다

print(c.numpy()) #b'Hello,world!'
#>> c의 내용(값)만을 보고 싶다면, numpy()함수를 이용한다

tf.Tensor(b'Hello,world!', shape=(), dtype=string)
b'Hello,world!'


In [ ]:
#+번외
print(a.shape) #형태만 출력
print(a.dtype) #내부데이터 타입만 출력

()
<dtype: 'int32'>


In [ ]:
aa = tf.constant(5)
aa #마지막줄에 적으면 numpy도 함꼐 뜸! >> print했을 때는 맨 앞에 인자가 numpy 값을 의미!

<tf.Tensor: shape=(), dtype=int32, numpy=5>

배열

In [ ]:
a = tf.constant([1,2,3])
a.shape # TensorShape([3]) >>shape이 [n] 인 것을 보아 vector 타입이다!
#>>Vector / 1차원 Tensor

TensorShape([3])

In [ ]:
a = tf.constant([[1,2,3],[4,5,6]])
a.shape
#>>행렬 / 2차원 Tensor

TensorShape([2, 3])

In [ ]:
a = tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a.shape
#>>텐서 / 3차원 Tensor

TensorShape([2, 2, 3])

In [ ]:
a 

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

함수



1. tf.cond(pred, true_fn=None, false_fn=None, name=None) : 조건 연산

  *   pred를 검사해 참이면 true_fc 반환
  * 거짓이면 false_fc 반환



In [ ]:
x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool,lambda: tf.add(x,1.), lambda: tf.add(x,10.))
#bool을 검사해 참일 경우 x(1.0)+1.0 = 2.0 / 거짓일 경우 x(1.0)+10.0 = 11.0
#lambda
print(res)
print(res.numpy())

tf.Tensor(2.0, shape=(), dtype=float32)
2.0


In [ ]:
x = tf.constant(2)
y = tf.constant(5)

def f1() : return tf.multiply(x,17) #곱하기
def f2() : return tf.add(y,23) #더하기

r = tf.cond(tf.less(x,y),f1,f2)
#x와 y를 비교했을 때 (x<y) , x가 작으면 f1함수(x*17=34) 실행 , 그렇지 않으면 f2 함수(y+23=28) 실행
#less : 첫번째인자 < 두번째인자 의 논리 결과
r.numpy()

34



# 1차원 배열 텐서



In [ ]:
#1차원 배열 텐서
t = tf.constant([1,2,3])
t
# shape=(3,) → tuple이 주로 모양이 ()의 모양이 됨

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([5,6,7])

print((x+y).numpy()) #각 튜플의 요소끼리 더해져 결과 값이 나타난다

[ 6  8 10]


In [ ]:
a = tf.constant([5], dtype=tf.float32) # 1치원 벡터의 타입을 float32로 지정한다
b = tf.constant([10], dtype=tf.float32) # 마찬가지
c = tf.constant([2], dtype=tf.float32) # 마찬가지
print(a.numpy())

d = a*b+c #연산 진행

print(d) # 값은 52 고이고, 1차원 벡터이므로 1이라는 모양이 나온다
print(d.numpy()) #내부 값만을 출력

[5.]
tf.Tensor([52.], shape=(1,), dtype=float32)
[52.]


#텐서의 브로드캐스팅 ★매우중요!★
: 모양이 다르더라도 연산이 가능하도록 함

→ 즉 2차원 + 1차원 이더라도 임의로 맞출 수 있게끔 함

In [ ]:
x = tf.constant([[0],[10],[20],[30]]) #4행 1열
y = tf.constant([0,1,2]) #1행 3열

# x = 4행 1열을 4행 3열로 늘린다
# y = 1행 3열을 4행 3열로 늘린다
# x+y = 4행 3열이 된 x와 y의 각 자리의 내부 데이터를 더한다.
print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np

#numpy.arange() : 매개변수 -1까지의 숫자로 배열을 만듬 (여기선 0,1,2)
print(np.arange(3)) 

#numpy.ones() : 매개변수 만큼의 행렬을 만들어주고, 각 자리를 1.0으로 초기화 함 (여기선 3x3, 2차원 행렬)
print(np.ones((3,3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y) #x와 y를 브로드 캐스팅함

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
#★중간고사 때 브로드 캐스팅 문제 낸다! (반드시 이해하기)

x = tf.constant((np.arange(3))) #0,1,2
y = tf.constant([5], dtype=tf.int64) #5
print((x+y).numpy()) #5, 6, 7
print()

x = tf.constant((np.ones((3,3)))) #1.0의 수가 들어간 3행 3열
y = tf.constant(np.arange(3), dtype=tf.double) #1행 3열
#연산을 할 것이므로 type은 실수형인 double로 지정 / 동일한 타입이어여 연산이 가능!
print((x+y).numpy()) 
print()

#reshape() : 모양을 바꾸는 함수 (여기선 1행 3열의 1차원 벡터를 3행 1열로 바꿈)
x = tf.constant(np.arange(3).reshape(3, 1))
y = tf.constant(np.arange(3)) #1행 3열
print((x+y).numpy()) 

[5 6 7]

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = 2
b = 3
c = tf.add(a, b)
print(c.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=5>>
